### ISSUE TITLE
Region override not working?

### ISSUE THREAD

**Issue by martinb3** [jlinn/elasticsearch-cloud-rackspace#1]
Hi! First of all, thanks so much for writing this plugin for Elasticsearch. It's a great resource!

I'm trying it out right now, and I'm running into two questions --
- I'm assuming all of the documented configuration options go under 'rackspace.', i.e., elasticsearch.yml should look like:

``` yaml
rackspace.account: rackspaceusername
rackspace.base_path: /
rackspace.chunk_size: 100m
rackspace.compress: false
rackspace.concurrent_streams: 5
rackspace.container: containername
rackspace.enabled: true
rackspace.key: secret
rackspace.region: ORD
```

Is that right?
- Even after that and doing creating a backup repo in Elasticsearch like so, I'm seeing this plugin create my container and upload snapshot data to the `DFW` region:

``` bash
curl -XPUT 'http://localhost:9200/_snapshot/backuprepo' -d '{
    "type": "cloudFiles",
    "settings": {
        "container": "containername",
        "region": "ORD"
    }
}'
```

When I browse cloud files, everything has been uploaded to `DFW/containername`. I think thiss because jclouds defaults to DFW. Is there another override I'm missing?

Thanks!
@martinb3
